# 데이터 분석 패키지 준비하기  
---

|패키지|기능|주요 함수|
|---|---|---|
|numpy|배열 계산, 반올림,버리기|floor,ceil,power|
|pandas|데이터프레임으로 데이터 입력,가공|describe,groupby|
|matplotlib|그래프 그리기|plot,hist,bar|  

외에도 많은 패키지들이 있음  

# 넘파이로 배열 다루기  
---

## 넘파이로 배열 정의하기

In [1]:
import numpy as np

In [3]:
a=np.array([[2,3],[5,2]])

In [4]:
a

array([[2, 3],
       [5, 2]])

|2|3|
|---|---|
|5|2|

## 배열 슬라이싱하기  
---

In [5]:
d=np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]])
d

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 6, 7],
       [5, 7, 8, 9, 9]])

첫 번째 인덱스 : 행, 두 번째 인덱스 : 열

In [6]:
d[1][2]

5

In [7]:
d[1,2]

5

## 배열 크기 알아내기  
---

In [8]:
d=np.array([[2,3,4,5,6]])
d

array([[2, 3, 4, 5, 6]])

In [9]:
d.shape

(1, 5)

In [10]:
e=np.array([[1,2,3,4],[3,4,5,6]])
e

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [11]:
e.shape

(2, 4)